# Generated by Django 3.0.7 on 2020-06-22 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('One_Time', 'Onetime'), ('Adjustment', 'Adjustment')], max_length=10)),
                ('principle', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time', models.IntegerField(null=True)),
                ('interest_inadvance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('partnership_id', models.AutoField(primary_key=True, serialize=False)),
                ('partnership_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Partnership')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Partnership')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('transactions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100, null=True)),
                ('owner_type', models.CharField(choices=[('User', 'User'), ('Partnership', 'Partnership')], max_length=11)),
                ('partnership_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Partnership')),
                ('ref_cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.Customer')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Customer'),
        ),
    ]
