# Generated by Django 3.0.7 on 2020-06-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cust_id',
            new_name='cust',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='partnership_id',
            new_name='partnership',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ref_cust_id',
            new_name='ref_cust',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='transactions_id',
            new_name='transactions',
        ),
        migrations.RenameField(
            model_name='partnershipadmin',
            old_name='partnership_id',
            new_name='partnership',
        ),
        migrations.RenameField(
            model_name='partnershipadmin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='partnershipmapping',
            old_name='partnership_id',
            new_name='partnership',
        ),
        migrations.RenameField(
            model_name='partnershipmapping',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='acct_id',
            new_name='acct',
        ),
    ]
